---
- name: vars | OS-Specific
  include_vars: "{{ item }}"
  with_first_found:
    - "vars-{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "vars-{{ ansible_distribution }}.yml"
  tags: [vars]
- import_tasks: node_exporter.yml
