---
- name: binary | Download
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    checksum: "{{ node_exporter_checksum }}"
    dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    mode: '0644'

- name: binary | Unarchive
  unarchive:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp
    remote_src: yes

- name: binary | Install
  copy: 
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: /usr/local/bin/node_exporter
    remote_src: yes
    mode: '0755'

- name: group | Create
  group:
    name: node_exporter
    state: present

- name: user | Create
  user:
    name: node_exporter
    groups: node_exporter
    shell: /bin/false
    create_home: no

- name: service | Create
  template:
    src: node_exporter.service.j2
    dest: "{{ systemd_dir }}/system/node_exporter.service"

- name: service | Start
  systemd:
    state: started
    daemon_reload: yes
    name: node_exporter
